### ISSUE TITLE
fork worries ?

### ISSUE THREAD

**Issue by rasjani** [Sinap/kodiswift#1]
I've been writing pretty much all of my addons with xbmcswift and as you, have noticed that jbel has gone awol 2-4 years ago =)

I needed some features today that where in PR's against jbel (and not in pr's from few other forks) and noticed that you have been active recently on updating xbmcswift (and renaming it to kodiswift). One worry about this: older addons don't get fixes/new features without small rewrite.. Understandable approach but, yeah, can lead to frustrations =)

Anyway, my question: how soon you will be considering of trying to get kodiswift to be merged to official repos ?

**Comment by afrase** [comment]
I believe I've kept the API the same except for the ListItem properties. They are still there but will show a deprecation warning.

Added to the official Kodi repo? I think I need to do more testing before doing that. All of the existing tests pass but I haven't done much real testing with plugins.
