### ISSUE TITLE
Refactoring use of xbmcswift2

### ISSUE THREAD

**Issue by PanderMusubi** [Sinap/kodiswift#2]
I would like to refactor some plugins away from xbmcswift2 to kodiswift as to fix a bug such as https://github.com/DamonToumbourou/plugin.video.c31/issues/1

When will kodiswift be part of de the default Kodi repository so that a dependency on it will install it by default?

**Comment by PanderMusubi** [comment]
At the moment, only http://addons.kodi.tv/show/script.module.xbmcswift2/ and http://addons.kodi.tv/show/script.module.xbmcswift/ are in the kodi repo. Would you like help to get kodiswift into the kodi repo?

**Comment by afrase** [comment]
There seems to be more interest in this so I'll try to submit a pull request this week to get it into the Kodi repo. I just want to do a little more testing before submitting it.

**Comment by PanderMusubi** [comment]
Super!

**Comment by afrase** [comment]
I've submitted the pull request to get it added to the official repo here 
https://github.com/xbmc/repo-scripts/pull/197

Still waiting to see if it get's accepted.

**Comment by phil65** [comment]
It will. Sorry for the trouble in that PR, some people just want to scream at others without reasoning..

**Comment by phil65** [comment]
Do you already have a plugin ready which makes use of it? Once that is up I will pull.

**Comment by PanderMusubi** [comment]
The two of which I know of (one maintained by me) are waiting that it is available so that migration development and testing will be done with the exact version in Kodi. Is that enough to get the PR executed?

**Comment by phil65** [comment]
Just put up the PR for that plugin.

**Comment by PanderMusubi** [comment]
So this one can be closed as https://github.com/xbmc/repo-scripts/pull/197 takes care fo it?

See also related PR https://github.com/Sinap/kodiswift/pull/6
