### ISSUE TITLE
Bug: playable item can not play because "is_folder" always returns true.

### ISSUE THREAD

**Issue by jester-xbmc** [Sinap/kodiswift#23]
@Sinap Please see and fix comments made by @thongld here
https://github.com/Sinap/kodiswift/commit/02541153d481b940e1fcd6a6c89c7faf40469a96

Currently, playable items can't play due to is_folder always returning true, even if is_folder is set to false and playable to true.

Thanks

**Comment by jester-xbmc** [comment]
Any update on this ? I want to move away from xbmcswift2 but this issue is currently blocking releasing my add-ons ping @rasjani @afrase thanks

**Comment by rasjani** [comment]
fix is to rollback the broken commit and re-integration to kodi official repos .. i can't do either and @afrase has been awol for few months ..

**Comment by jester-xbmc** [comment]
Ah ha ! somebody is back from the dead ;-)

Thanks @afrase !
