### ISSUE TITLE
Everything is a folder.

### ISSUE THREAD

**Issue by JohnDoee** [Sinap/kodiswift#27]
the is_playable option does not set an item as a file as it should.

https://github.com/Sinap/kodiswift/blob/cb4cac4022daa638ee614aa0a24a16d02d259647/kodiswift/listitem.py#L306 <- this line is missing listitem.is_folder = False

**Comment by rasjani** [comment]
Duplicate of #23

**Comment by JohnDoee** [comment]
hah, my bad, not sure how I missed that.

**Comment by rasjani** [comment]
I'll check on this tomorrow, just adding the listem.is_folder might not cover all cases  as there are setters too & im not really familiar how is_folder & is_playable really work together ..  I also have some stuff coming out soon and need this to be fixed before i can release new stuff..

**Comment by JohnDoee** [comment]
The bug seems to only be in `ListItem.from_dict` and not any other code-paths. So, it's only when you use the shortcut to create items that you can't make files.

#21 mentions being in complete control of `playable` and `is_folder`, something you can only be if you manually create the `ListItem`.
