### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jindaxia** [Sinap/kodiswift#4]
I was adding "poster","Landscape" ... supporting to xbmcswift2, before I saw your fork

**Comment by jindaxia** [comment]
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                           Error Type: <type 'exceptions.WindowsError'>
>                                           Error Contents: (183, '')
>                                           Traceback (most recent call last):
>                                             File "D:\Program Files (x86)\Kodi17\portable_data\addons\plugin.video.bigmovies\default.py", line 6, in <module>
>                                               plugin.run()
>                                             File "D:\Program Files (x86)\Kodi17\portable_data\addons\plugin.video.bigmovies\kodiswift\plugin.py", line 314, in run
>                                               storage.close()
>                                             File "D:\Program Files (x86)\Kodi17\portable_data\addons\plugin.video.bigmovies\kodiswift\storage.py", line 105, in close
>                                               self.sync()
>                                             File "D:\Program Files (x86)\Kodi17\portable_data\addons\plugin.video.bigmovies\kodiswift\storage.py", line 163, in sync
>                                               super(TimedStorage, self).sync()
>                                             File "D:\Program Files (x86)\Kodi17\portable_data\addons\plugin.video.bigmovies\kodiswift\storage.py", line 123, in sync
>                                               os.rename(temp_file, self.file_path)
>                                           WindowsError: (183, '')

**Comment by jindaxia** [comment]
#5 I just open a PR to fix this

**Comment by afrase** [comment]
Thanks, PR merged.
